config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, :controllers => { :registrations => 'registrations' }
  get 'home/index', as: :video_home

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :api do
      get "videos" => 'videos#index'
      post "videos" => 'videos#create'
      put "videos/:id" => 'videos#update'
    end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
  belongs_to :user

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create email: email, card: token
    customer.subscriptions.create({:plan => "premium"})
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

has_one :payment
accepts_nested_attributes_for :payment

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/api/videos_controller.rb
class Api::VideosController < ApplicationController
  skip_before_filter :authenticate_user!

protect_from_forgery with: :reset_session

  def index
    @videos = Video.all
    render json: @videos
  end

  def show
    @videos = Video.all
  end

  def create
    @video = Video.new(params.require(:video).permit(:title, :thumbnail, :videourl, :category, :description))
    @video.save
    render json: @video
  end

  def update
    @video = Video.find(params[:id])
    @video.update(params.require(:video).permit(:title, :thumbnail, :videourl, :category, :description))
    render json: @video
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
    end


    def after_sign_in_path_for(resource)
      :video_home
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @videos = Video.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new({ email: params["user"]["email"],
          token: params[:payment]["token"], user_id: resource.id })

        flash[:error] = "Please check registration errors" unless @payment.valid?

        begin
          @payment.process_payment
          @payment.save
        rescue Exception => e
          flash[:error] = e.message

          resource.destroy
          puts 'Payment failed'
          render :new and return
        end

        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:payment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    render layout: false
  end
end

app/helpers/api/videos_helper.rb
module Api::VideosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <% @videos.each do |f| %>

    <div class="img-thumbnail col-sm-6 col-md-3 videocontainer">
      <center>
        <%= image_tag f.thumbnail, class:"img-responsive thumb", "data-toggle"=>"modal", "data-target"=>"#modal-#{f.id}" %>
      <hr>
        <b> <div class="uptext">  <%= f.title%> </div> </b>
      </center>
    </div>

  <center>
    <div class="modal fade jsmodal" id="modal-<%=f.id%>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="img-lrg modal-content">
          <%= video_tag f.videourl, controls: true, autobuffer: true, poster: "#{f.thumbnail}",class: "videosize" %>
            <hr />
            <h1> <%= f.title %> </h1>
            <div style="text-align: left; padding: 0em 1em 1em 1em;">  <%= f.description %> </div>
        </div>
      </div>
    </div>
  </center>

  <% end %>

</div><!-- Container Div -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimalTV</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="//jashkenas.github.io/underscore/underscore-min.js"></script>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="container">
  <div class="navbar-text pull-left">
    <% if user_signed_in? %>
    <a href="/home/index"><%= image_tag "logo-01.png", class: "logo img-responsive"%></a>
    <% else %>
    <a href="/"><%= image_tag "logo-01.png", class: "logo img-responsive"%></a>
    <% end %>
  </div>

  <div class="navbar-text pull-right">

  <% if user_signed_in? %>
  <%= link_to 'Admin Panel', rails_admin_path, :class => 'navbar-link btn btn-success' if current_user.admin == true %>

    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn btn-default' %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-danger'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn btn-primary'  %>
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link btn btn-success'  %>
  <% end %>
  </div>
</div>




<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimalTV</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="//jashkenas.github.io/underscore/underscore-min.js"></script>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>











<section class="hero-section">
  <div class="header-unit">

    <div class="row hero-text-box text-center">
      <a href="/">
        <%= image_tag "logo-01.png", style: "max-width: 25em; img-responsive"%>
      </a>
      <h2> Fitness on the go. </h2>
      <br>

      <div>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn btn-primary'  %>
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link btn btn-success'  %>
      </div>

    </div>

    <div class="header-unit beforevideo">
    </div>

    <div id="video-container">
      <video id="hdr" autoplay loop class="fillWidth" muted="muted" volume="0">
      <source src="http://earoa.com/primaltv/videos/commercial_cut.mp4" type="video/mp4"/>
      <source src="http://earoa.com/primaltv/videos/commercial_cut.mp4" type="video/ogg"/>
      <source src="http://earoa.com/primaltv/videos/commercial_cut.mp4" type="video/webm"/>
      Your browser does not support the video tag. I suggest you upgrade your browser.
    </video>
    </div><!-- end video-container -->
  </div><!-- end .header-unit -->

</section>


</body>
</html>